## MIIA-4203 MODELOS AVANZADOS PARA ANÁLISIS DE DATOS II


# Introducción a Sistemas de Recomendación

## Actividad 10


### Profesor: Camilo Franco (c.franco31@uniandes.edu.co)

## Actividad en grupos
### Nombres:

- Nelson Aldana
- Diego Ojeda
- Daniel Rojas

**Instrucciones:** Por favor escriba los nombres de los integrantes de su grupo. Esta actividad debe ser entregada a más tardar dentro de 8 días, con la respuesta para los ejercicios y preguntas en cada numeral.

En este cuadernos estudiaremos una primera introducción a los sistemas de recomendación, examinando un modelo de recomendación en base a la popularidad, sin ningún grado de personalización. En futuras actividades exploraremos otros sistemas basados en contenido o en filtrado colaborativo, los cuales toman en cuenta las preferencias de los usuarios. 

Los sistemas de recomendación están entre las aplicaciones más populares de la ciencia de datos actualmente. El marco que ofrecen estos sistemas permite representar modelos de decisión junto con métodos estadístico/computacionales para **aprender y estimar** las preferencias de los usuarios.

## Introducción

En esta introducción vamos a construir un modelo simple basado en popularidad. Aprenderemos nociones que nos permitirán construir modelos más complejos de recomendación. 

En este cuaderno vamos a trabajar con una base de datos de películas IMDB (https://www.imdb.com/) 

En términos generales, los sistemas de recomendación pueden clasificarse en 3 tipos:

- **Recomendadores simples:** genera recomendaciones para cada usuario según la popularidad del ítem o producto. Por ejemplo, proponer películas o un género en base a su popularidad o su crítica, donde una buena crítica aproxima una mayor probabilidad de que la película sea apreciada por una audiencia "promedio".
- **Recomendadores basados en contenido:** sugiere elementos similares en función de un elemento en particular, como por ejemplo el género, la sinopsis o el reparto (actores, etc). De esta manera, si el usuario tiene unas preferencias específicas sobre un ítem/artículo en particular, también podría tener preferencia por un ítem *similar*.
- **Recomendadores por filtrado colaborativo:** estos sistemas generan recomendaciones a partir de similitudes entre usuarios, prediciendo la calificación o preferencia de un usuario sobre un ítem, o un grupo de atributos de dicho ítem, según las calificaciones y preferencias observadas de otros usuarios. 

Por último se puede considerar también un cuarto tipo de recomendadores, que son los de tipo **Híbrido**. Estos hacen referencia al uso simultaneo de las distintas metodologias antes señaladas y de múltiples fuentes de información o tecnologías específicas, como pueden ser las redes sociales o fuentes de información geográfica, demográfica, etc.

Para profundizar en los sistemas de recomendación se pueden consultar las siguientes fuentes:
- Ch. Aggarwal. Recommender Systems. Springer, 2016.
- J. Leskovec, A. Rajaraman, J. Ullman. Mining of Massive Datasets. Cambridge University Press (http://www.mmds.org/)

## 1. Sistema de recomendación simple

Los recomendadores simples generan recomendaciones basadas en su popularidad, de acuerdo con una *preferencia promedio*. 

La pregunta es,

**¿cómo medimos la popularidad de un producto/ítem?**

Una opción es la de elegir una métrica determinada para puntuar las películas, y en base a esa métrica generar un valor de preferencia por el ítem. De esta manera es posible consturir un *orden lineal* o un *ranking estricto* con las mejores películas de la base de datos IMDB.

Pasos a seguir:
- Elegir la métrica con la que se va a calificar cada película. Este punto también se puede entender como un modelo para estimar las preferencias por una película.
- Calcular el valor de preferencia sobre cada película.
- Ordenar las películas según su valor o puntuación y obtener una lista con las mejores k peliculas.

Manos a la obra, primero carguemos el conjunto de datos como un data frame en la bilbioteca Pandas:

In [68]:
# Importamos la biblioteca Pandas
import pandas as pd

# Cargamos los datos de peliculas de la base de datos IMDB
metadata = pd.read_csv('movies_metadata.csv', low_memory=False)

print(metadata.shape)
      
list(metadata)

(45466, 24)

['adult',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'id',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'video',
 'vote_average',
 'vote_count']

In [69]:
# Así se ven los datos
metadata.head(3)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0

In [70]:
metadata[['original_title', 'popularity']][1:10]

                original_title popularity
1                      Jumanji  17.015539
2             Grumpier Old Men    11.7129
3            Waiting to Exhale   3.859495
4  Father of the Bride Part II   8.387519
5                         Heat  17.924927
6                      Sabrina   6.677277
7                 Tom and Huck   2.561161
8                 Sudden Death    5.23158
9                    GoldenEye  14.686036

### Rating vs. Popularidad

Con esta información vamos a construir un sistema que recomiende películas basados directamente en su *rating*, o **voto promedio**. Sin embargo, es cierto que hay otro atributo relevante como lo es el de su **popularidad**. Por ejemplo, si un solo usuario califica con 10 una pelicula, pero 5000 usuarios le dan en promedio un 8.3, solo en base al rating la primera película sería considerada mejor que la segunda.


Bajo una perspectiva de *los grandes números*, la valoración o voto promedio de una película tiende a converger hacia un valor que refleje la calidad de la película a medida que el número de votos aumenta. Con poca información, o pocos votos, es más difícil estimar la calidad promedio de la película.  


Entonces, 

**¿qué tipo de métrica nos sirve para evaluar apropiadamente la preferencia por una película?** 

Tengamos en cuenta que en base a esta métrica se tendrán mejores o peores recomendaciones!

### Ejercicio 1.1

Examine los datos y proponga una métrica que permita estimar la preferencia promedio por una película.

In [71]:
metadata.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

### Seleccionamos la métrica asociada a la popularidad ponderada por el conteo de votos

In [72]:
# Calificacion de peliculas basada en la ponderacion de su popularidad 
def rating_popular(x):
    """
    Input:
    x: datos de popularity y votacion de las peliculas
    m: minimo numero de votos
    Output:
    popularity ponderado
    """
    
    x['popularity'] = x['popularity'].astype(float)
    
    m = x['popularity'].max()
    v = x['vote_count']
    R = x['popularity']
    
    return (v/(v+m) * R)

### Ponderación entre rating y popularidad

Una opción puede consistir en ponderar el rating que recibe una película por su número de votos. De esta manera se pueden prevenir situaciones donde una película con un voto de 10 obtenga una mejor calificación que una película con 1000 votos con un promedio de 9.5.  

De esta manera, el voto promedio ponderado $\mu_i$, de la $i$-ésima película lo definimos como:

$$
\mu_i  = \left( \frac{v_i}{v_{max}} \right) R_i 
$$

donde $v_i$ es el número de votos para la $i$-ésima película, $v_{max}$ es el máximo número de votos que recibe la película más popular, y $R$ es el rating promedio de la pelicula.


En la base de datos tenemos los valores de $v_i$ (vote_count) y $R$ (vote_average) para cada pelicula. Además podemos agregar un filtro para que considere las películas con un minimo número de votos $v_{min}$.

Nos quedamos con las columnas necesarias para calcular el rating ponderado más el link de la pagina (en caso de que esté disponible):

In [73]:
pelisR = metadata[['original_title', 'homepage', 'vote_count', 'vote_average']]
pelisR.shape

(45466, 4)

In [74]:
# Calificacion de peliculas basada en la ponderacion de su rating 
def rating_ponderado(x):
    """
    Input:
    x: datos de rating y votacion de las peliculas
    m: minimo numero de votos
    Output:
    rating ponderado
    """
    m = x['vote_average'].max()
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R)

Definimos una nueva respuesta 'score' y calculamos su valor con la funcion rating_ponderado().

A continuación ordenamos las películas basados en el score y ofrecemos el top 15 de películas preferidas:

In [75]:
import warnings
warnings.filterwarnings("ignore", category=Warning)

# si tiene al menos vmin votos, incluimos la pelicula
vmin = 1
pelisRF = pelisR.copy().loc[pelisR['vote_count'] >= vmin]
pelisRF['score'] = rating_ponderado(pelisRF)

# ordenamos las peliculas de acuerdo con el score
pelisRF = pelisRF.sort_values('score', ascending=False)

# Mostramos el top15 de las peliculas
pelisRF[['original_title', 'homepage', 'vote_count', 'vote_average', 'score']].head(15)

,original_title,homepage,vote_count,vote_average,score
10309,Dilwale Dulhania Le Jayenge,NaN,661.0,9.1,8.964382
314,The Shawshank Redemption,NaN,8358.0,8.5,8.489842
834,The Godfather,http://www.thegodfather.com/,6024.0,8.5,8.485913
40251,君の名は。,https://www.funimationfilms.com/movie/yourname/,1030.0,8.5,8.418269
39085,Planet Earth,NaN,176.0,8.8,8.326882
12481,The Dark Knight,http://thedarkknight.warnerbros.com/dvdsite/,12269.0,8.3,8.293240
2843,Fight Club,http://www.foxmovies.com/movies/fight-club,9678.0,8.3,8.291433
292,Pulp Fiction,NaN,8670.0,8.3,8.290438
522,Schindler's List,http://www.schindlerslist.com/,4436.0,8.3,8.281332
23673,Whiplash,http://sonyclassics.com/whiplash/,4376.0,8.3,8.281076
5481,千と千尋の神隠し,http://movies.disney.com/spirited-away,3968.0,8.3,8.279135
2211,La vita è bella,NaN,3643.0,8.3,8.277279
1178,The Godfather: Part II,NaN,3418.0,8.3,8.275788
1152,One Flew Over the Cuckoo's Nest,NaN,3001.0,8.3,8.272434
1176,Psycho,NaN,2405.0,8.3,8.265631

Examinemos el efecto de cambiar el mínimo numero de votos a considerar:

In [76]:
# Si tiene al menos mil votos incluimos la pelicula
vmin = 1000
pelisRF = pelisR.copy().loc[pelisR['vote_count'] >= vmin]
pelisRF['score'] = rating_ponderado(pelisRF)

# ordenamos las peliculas de acuerdo con el score
pelisRF = pelisRF.sort_values('score', ascending=False)

# Mostramos el top15 de las peliculas
pelisRF[['original_title', 'homepage', 'vote_count', 'vote_average', 'score']].head(15)

,original_title,homepage,vote_count,vote_average,score
314,The Shawshank Redemption,NaN,8358.0,8.5,8.491364
834,The Godfather,http://www.thegodfather.com/,6024.0,8.5,8.488023
40251,君の名は。,https://www.funimationfilms.com/movie/yourname/,1030.0,8.5,8.430429
12481,The Dark Knight,http://thedarkknight.warnerbros.com/dvdsite/,12269.0,8.3,8.294254
2843,Fight Club,http://www.foxmovies.com/movies/fight-club,9678.0,8.3,8.292717
292,Pulp Fiction,NaN,8670.0,8.3,8.291871
522,Schindler's List,http://www.schindlerslist.com/,4436.0,8.3,8.284126
23673,Whiplash,http://sonyclassics.com/whiplash/,4376.0,8.3,8.283909
5481,千と千尋の神隠し,http://movies.disney.com/spirited-away,3968.0,8.3,8.282258
2211,La vita è bella,NaN,3643.0,8.3,8.280679
1178,The Godfather: Part II,NaN,3418.0,8.3,8.279410
1152,One Flew Over the Cuckoo's Nest,NaN,3001.0,8.3,8.276558
1176,Psycho,NaN,2405.0,8.3,8.270769
1184,Once Upon a Time in America,NaN,1104.0,8.3,8.236584
351,Forrest Gump,NaN,8147.0,8.2,8.191454

Veamos en qué consiste esa pelicula en japonés:

In [77]:
#import webbrowser

#webbrowser.open(pelisRF['homepage'][23673])

### Ejercicio 1.2

Examine cómo varían los resultados si tomamos directamente la variable de popularidad.

In [78]:
pelisR = metadata[['original_title', 'homepage', 'vote_count',"vote_average", 'popularity']]

pelisRF = pelisR.copy().loc[pelisR['vote_count'] >= vmin]

# Ajustando los valores anomalos
pelisRF.popularity[536]=str(float(pelisRF.popularity[536])/10)

# ordenamos las peliculas de acuerdo con el score
pelisRF = pelisRF.sort_values('popularity', ascending=False)

# Mostramos el top15 de las peliculas
pelisRF.head(15)

,original_title,homepage,vote_count,vote_average,popularity
3893,What Women Want,NaN,1021.0,6.1,9.963079
21162,White House Down,NaN,1910.0,6.3,9.920223
12356,Rambo,http://www.rambofilm.com/,1009.0,6.4,9.91556
37927,Neighbors 2: Sorority Rising,http://www.neighbors-movie.com/,1490.0,5.6,9.914008
12368,In Bruges,http://www.filminfocus.com/film/in_bruges,1414.0,7.4,9.895652
2586,Wild Wild West,NaN,1042.0,5.1,9.887602
2556,Notting Hill,http://www.notting-hill.com/,1309.0,7.0,9.874043
9542,The Aviator,NaN,1526.0,7.0,9.86738
13507,Män som hatar kvinnor,http://dragontattoofilm.com/,1020.0,7.4,9.858687
17358,Horrible Bosses,http://horriblebossesmovie.warnerbros.com/inde...,2341.0,6.4,9.856955
227,Dumb and Dumber,NaN,1894.0,6.5,9.844558
608,The Aristocats,NaN,1287.0,7.1,9.834047
16760,The Mechanic,http://www.themechanicmovie.com/,1066.0,6.3,9.832342
21163,The World's End,NaN,1820.0,6.7,9.830382
13502,Knowing,http://knowing-themovie.com/,1528.0,5.9,9.806904

### Recomendación de peliculas mas populares por genero

In [79]:
import numpy as np
from ast import literal_eval

# trabajamos la informacion por generos
metadata['genres'] = metadata['genres'].fillna('[]').apply(literal_eval).apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

# añadimos la variable del año
metadata['year'] = pd.to_datetime(metadata['release_date'], errors='coerce').apply(lambda x: str(x).split('-')[0] if x != np.nan else np.nan)

metadata.head(3)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,1995
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,1995

Primero nos quedamos con todos los generos:

In [80]:
generos = metadata.apply(lambda x: pd.Series(x['genres']),axis=1).stack().reset_index(level=1, drop=True)
generos.name = 'genre'
gen_md = metadata.drop('genres', axis=1).join(generos)

gen_md.head(3)

,adult,belongs_to_collection,budget,homepage,id,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year,genre
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995,Animation
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995,Comedy
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995,Family

In [81]:
generos

0        Animation
0           Comedy
0           Family
1        Adventure
1          Fantasy
           ...
45461       Family
45462        Drama
45463       Action
45463        Drama
45463     Thriller
Name: genre, Length: 91106, dtype: object

Construimos una funcion para un género particular y que tome en cuenta peliculas con un número vmin de votos:

In [ ]:
def rec_gen(genero, vmin):
    df = gen_md[gen_md['genre'] == genero]
    v = df[df['vote_count'].notnull()]['vote_count'].astype('int')
    R = df[df['vote_average'].notnull()]['vote_average'].astype('int')
    m = df['vote_average'].max()
    
    pelisG = df[(df['vote_count'] >= vmin) & (df['vote_count'].notnull()) & (df['vote_average'].notnull())][['title', 'year', 'vote_count', 'vote_average', 'popularity', 'overview', 'homepage']]
    pelisG['vote_count'] = pelisG['vote_count'].astype('int')
    pelisG['vote_average'] = pelisG['vote_average'].astype('int')
    
    pelisG['wr'] = v/m * R
    pelisG = pelisG.sort_values('wr', ascending=False).head(250)
    
    return pelisG

Veamos el Top-15 de recomendaciones en Ciencia Ficción:

In [ ]:
k = 15
scifi = rec_gen('Science Fiction', 1000)
scifi.head(k)

Inception e Interstellar aparecen en las dos primeras posiciones. Personalmente me gusta más Interstellar (si quieres ver un agujero negro, esta película es lo mejor que podrás conseguir), pero reconozco que Inception tiene mucho nivel. Podemos seguir refinando este tipo de recomendaciones prestando atención a los distintos atributos que tenemos disponibles sobre las películas.

### Ejercicio 1.3

Elija el género de su interés y aplique la métrica propuesta en el Ejercicio 1.1

In [100]:
import warnings
warnings.filterwarnings("ignore", category=Warning)

# si tiene al menos vmin votos, incluimos la pelicula
vmin = 1
pelisRF = pelisR.copy().loc[pelisR['vote_count'] >= vmin]

# Aplicamos la metrica de la popularidad ponderada por el voto promedio
pelisRF['score'] = rating_popular(pelisRF)

# ordenamos las peliculas de acuerdo con el score
pelisRF = pelisRF.sort_values('score', ascending=False)

# Mostramos el top15 de las peliculas
pelisRF[['original_title', 'homepage', 'vote_count', 'vote_average',"popularity", 'score']].head(15)

,original_title,homepage,vote_count,vote_average,popularity,score
30700,Minions,http://www.minionsmovie.com/,4729.0,6.4,547.488298,490.680925
33356,Wonder Woman,http://www.warnerbros.com/wonder-woman,5025.0,7.2,294.337037,265.418881
42222,Beauty and the Beast,http://movies.disney.com/beauty-and-the-beast-...,5530.0,6.8,287.253654,261.376514
24455,Big Hero 6,http://movies.disney.com/big-hero-6,6289.0,7.8,213.849907,196.724108
43644,Baby Driver,NaN,2083.0,7.2,228.032744,180.571876
26564,Deadpool,http://www.foxmovies.com/movies/deadpool,11444.0,7.4,187.860492,179.283456
14551,Avatar,http://www.avatarmovie.com/,12114.0,7.2,185.070892,177.068346
24351,John Wick,http://www.johnwickthemovie.com/,5499.0,7.0,183.870374,167.221557
26566,Guardians of the Galaxy Vol. 2,http://marvel.com/movies/movie/221/guardians_o...,4858.0,7.6,185.330992,166.559968
23675,Gone Girl,http://www.gonegirlmovie.com/,6023.0,7.9,154.801009,141.902159
26567,Captain America: Civil War,http://marvel.com/captainamericapremiere,7462.0,7.1,145.882135,135.910367
24873,The Hunger Games: Mockingjay - Part 1,http://www.thehungergames.movie/,5767.0,6.6,147.098006,134.344093
292,Pulp Fiction,NaN,8670.0,8.3,140.950236,132.578258
12481,The Dark Knight,http://thedarkknight.warnerbros.com/dvdsite/,12269.0,8.3,123.167259,117.905862
26560,Pirates of the Caribbean: Dead Men Tell No Tales,http://pirates.disney.com/pirates-of-the-carib...,2814.0,6.6,133.827820,112.031176

In [101]:
def rec_gen_pop(genero, vmin):
    df = gen_md[gen_md['genre'] == genero]
    df['popularity'] = df['popularity'].astype(float)
    v = df[df['vote_count'].notnull()]['vote_count'].astype('int')
    R = df[df['popularity'].notnull()]['popularity'].astype('float')
    m = df['popularity'].max()
    
    pelisG = df[(df['vote_count'] >= vmin) & (df['vote_count'].notnull()) & (df['vote_average'].notnull())][['title', 'year', 'vote_count', 'vote_average', 'popularity', 'overview', 'homepage']]
    pelisG['vote_count'] = pelisG['vote_count'].astype('int')
    pelisG['popularity'] = pelisG['popularity'].astype('float')
    
    pelisG['wr'] = v/m * R
    pelisG = pelisG.sort_values('wr', ascending=False).head(250)
    
    return pelisG

In [102]:
k = 15
scifi = rec_gen_pop('Science Fiction', 1000)
scifi.head(15)

,title,year,vote_count,vote_average,popularity,overview,homepage,wr
14551,Avatar,2009,12114,7.2,185.070892,"In the 22nd century, a paraplegic Marine is di...",http://www.avatarmovie.com/,12096.998788
26567,Captain America: Civil War,2016,7462,7.1,145.882135,"Following the events of Age of Ultron, the col...",http://marvel.com/captainamericapremiere,5873.666782
17818,The Avengers,2012,12000,7.4,89.887648,When an unexpected enemy emerges and threatens...,http://marvel.com/avengers_movie/,5820.137066
26566,Guardians of the Galaxy Vol. 2,2017,4858,7.6,185.330992,The Guardians must fight to keep their newfoun...,http://marvel.com/movies/movie/221/guardians_o...,4858.000000
24873,The Hunger Games: Mockingjay - Part 1,2014,5767,6.6,147.098006,Katniss Everdeen reluctantly becomes the symbo...,http://www.thehungergames.movie/,4577.292721
23753,Guardians of the Galaxy,2014,10014,7.9,53.291601,"Light years from Earth, 26 years after being a...",http://marvel.com/guardians,2879.508099
24121,The Maze Runner,2014,5540,7.0,76.937890,"Set in a post-apocalyptic world, young Thomas ...",http://themazerunnermovie.com/,2299.863104
15480,Inception,2010,14075,8.1,29.108149,"Cobb, a skilled thief who commits corporate es...",http://inceptionmovie.warnerbros.com/,2210.624315
536,Blade Runner,1982,3833,7.9,96.272374,In the smog-choked dystopian Los Angeles of 20...,http://www.warnerbros.com/blade-runner,1991.097148
22879,Interstellar,2014,11187,8.1,32.213481,Interstellar chronicles the adventures of a gr...,http://www.interstellarmovie.net/,1944.478946
42170,Logan,2017,6310,7.6,54.581997,"In the near future, a weary Logan cares for an...",http://www.foxmovies.com/movies/logan,1858.363770
23692,Dawn of the Planet of the Apes,2014,4511,7.3,75.385211,A group of scientists in San Francisco struggl...,http://www.dawnofapes.com/,1834.893793
30543,Suicide Squad,2016,7717,5.9,42.965027,"From DC Comics comes the Suicide Squad, an ant...",http://www.suicidesquad.com/,1789.021414
2458,The Matrix,1999,9079,7.9,33.366332,"Set in the 22nd century, The Matrix tells the ...",http://www.warnerbros.com/matrix,1634.550838
25084,Jurassic World,2015,8842,6.5,32.790475,Twenty-two years after the events of Jurassic ...,http://www.jurassicworld.com/,1564.408504

Podemos observar que al cambiar la métrica las recomendaciones cambian, pero siguen teniendo sentido los resultados, ya que *Avatar* si que es una pelicula de ciencia ficcion junto con *Captain America: Civil War* & *The Avengers*, si que son ficcion!